grass:
  growRate: 1
  repletion: 0.5

water:
  count:
    min: 35
    max: 40
  radius:
    min: 2
    max: 3

rabbit:
  sightRadius: 3
  age:
    coefficient: 1.25
    min: 20
    max: 40
  hunger:
    gain: 0.001
    limit: 1
  thirst:
    gain: 0.01
    limit: 1

fox:
