grass:
  growRate: 0.25
  repletion: 0.5

water:
  count:
    min: 35
    max: 40
  radius:
    min: 2
    max: 3

rabbit:
  sightRadius: 3
  hunger:
    gain: 0.1
    limit: 1
  thirst:
    gain: 0.1
    limit: 1

fox:
