grass:
  growRate: 1
  repletion: 0.5

water:
  repletion: 0.5
  count:
    min: 35
    max: 40
  radius:
    min: 2
    max: 3

rabbit:
  sightRadius: 3
  age:
    coefficient: 1.25
    min: 200
    max: 400
  hunger:
    gain: 0.1
    limit: 1
  thirst:
    gain: 0.05
    limit: 1

fox:
